GET http://localhost:3000/items/1.json

###

GET http://localhost:3000/items.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "Test 2 name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}

###

GET http://localhost:3000/users/6
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NTI5NjgwMDV9.zXyksQd9cVhAzcMP2kAmADFqynQBDXmsglEZqtXo1aE