Image.create!([
  {url: "https://www.dreamguitars.com/shop/media/catalog/product/cache/1/thumbnail/540x720/17f82f742ffe127f42dca9de82fb58b1/i/m/image_full_4193.jpg", item_id: 1},
  {url: "https://cdn11.bigcommerce.com/s-dks6ju/images/stencil/1280x1280/products/6354/60147/1__45220.1639698390.JPG?c=2", item_id: 1},
  {url: "https://static.wixstatic.com/media/db0e5b_d1b16b1c1cf54e4cb0227da667084b3a~mv2.jpg/v1/fill/w_560,h_527,al_c,q_80,enc_auto/db0e5b_d1b16b1c1cf54e4cb0227da667084b3a~mv2.jpg", item_id: 2},
  {url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmoI0TWu-Igympp08hcA2DMiHsK-zylYGyBQkF_i_dGThCPCPkaXWQPh0Z3Llew2NnRZ0&usqp=CAU", item_id: 2},
  {url: "https://static.wixstatic.com/media/db0e5b_4a37eba1e2784339b8a4e785d3bd718e~mv2.jpg/v1/fill/w_640,h_602,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/db0e5b_4a37eba1e2784339b8a4e785d3bd718e~mv2.jpg", item_id: 3},
  {url: "https://encrypted-tbn0.gstatic.com/image\ns?q=tbn:ANd9GcQFJuYPqtoM9TpWC01HbedCXMlF6Z8ltYldNA&usqp=CAU", item_id: 3},
  {url: "https://images.reverb.com/image/upload/s--lsvYexOA--/a_exif,c_limit,e_unsharp_mask:80,f_auto,fl_progressive,g_south,h_1600,q_80,w_1600/v1423528311/ctx7gddw157ydpsatsar.jpg", item_id: 1}
])
Category.create!([
  {name: "Tricone"},
  {name: "Biscuit Cone"},
  {name: "Spider Cone"},
  {name: "Folk"}
])
Item.create!([
  {name: "Style 1 Tricone", manufacturer: "National", year: 1927, description: "After coming across the new Hawaiian lapsteels, Los Angeles inventor John Dopyera decided to investigate ways of amplifying the popular slide guitar sound. Once he saw a violin with an attatched amplifying horn, Dopyera began to work on his inverted cone designs. Dopyera was assisted with his nephews Paul and Carl Barth spinning the first aluminum diaphragms on wooden bucks. They first experimented with their novel ampli-phonic design in a large walnut console instrument. Soon afterwards the first German silver Hawaiian guitar was built by John and Rudolph Dopyera. This guitar, #101 was later modified with a mahogany Spanish neck for regular guitar playing. George Beauchamp, Dopyera's business partner, had suggested to Dopyera the need for a guitar loud enough to play a melody over brass and other wind instruments. In 1927, National produced the first resonator instruments and sold them under their National brand. They had metal bodies and a tricone resonator system, with three aluminium cones joined by a T-shaped aluminium spider. This is the Style 1 tricone, a guitar with a unique chiming sound in between the sustain of the spider bridges and the banjo like punch of the buscuit bridges. The oniginal German Silver tricone s are still frequently sought after by collectors.", category_id: 1},
  {name: "Style 1 Tricone Reissue", manufacturer: "National", year: 2008, description: "When he invented \nthe original National Tricone all the way back in 1927, John Dopyera was seeking to create a louder guitar with internal amplification \n— but he also insisted that the guitar’s tone be absolutely clear. His groundbreaking design patented in 1927 with three resonating con\nes projected the guitar’s sound so it could be over the sound of dancers and cut through a band or orchestra. As John rightly boasted, \n“The Tricone guitar flowed like a river,” and the company’s early ads proclaimed it “The Greatest Musical Sensation of the Age.” Now, n\ninety years later, Tricones are still revered by musicians everywhere for that special sound. ike the originals, our Style 1 Tricone is\n built with a Brass body and coverplate — the same, unique alloy used by the Dopyera Brothers. And like those guitars, our body, coverp\nlate, and tailpiece are nickel plated and polished to a mirror-like shine. The mahogany neck is finished in a rich, warm burst and fitt\ned with an ivoroid-bound ebony fingerboard. The vintage-style tuning machines work on the classic slotted headstock, topped by the fame\nd National shield decal. An early National advertisement in 1927 touted the Tricone’s tone, power, and quality of sound, and our new re\nissues proudly carry on that tradition.", category_id: 1},
  {name: "Style 0 Single Cone", manufacturer: "National", year: 2021, description: "Gazing upon the famous Style “O,” one can almost hear the sweet song of the Hawaiian breeze through the swaying palm trees, syncopated to the soft roll of the waves upon the sandy shore as the sun sets in the distance. When National first introduced the Style “O” in 1930, the catalog promised it was “sure to win the admiration of everyone because of its beauty of design and marvelous tone quality.” And advertisements soon proclaimed it National’s “best seller ever!”. Now, more than 80 years later, that’s as true as ever. The Style “O” remains National’s flagship — and through the decades, it has become of the most iconic, most recognized guitars of all time. Just like the original, today’s Style “O” features a brass body polished to a mirror-like shine, plated in nickel, and finally etched with that famous scene depicting the allure of the Aloha Isles. The maple neck is finished in a traditional sunburst and capped by an ivoroid-bound ebony fretboard topped by vintage-style engraved tuners. Thanks to both its look and sound, the Style “O” remains a timeless classic.", category_id: 2},
  {name: "Tricone Custom", manufacturer: "Beard", year: 2017, description: "A beautiful high tier Beard tiecone model feauturing legendary Beard spun cones in the Beard Triphonic style. Other than getting a late 20s National in great condition (increasingly rare), this is your best chance to play the highest quality tricone resonator around.", category_id: 1},
  {name: "RM-991 Nickel Tricone Resonator", manufacturer: "Recording King", year: 2020, description: "This California company makes affordable verions of high end guitars and other folk instruments. Being essentially a copy of the original Nationals, I was pleseantly suprised by this guitar's buld quality and playability. Keep an eye on these guys.", category_id: 1},
  {name: "G9201 Honey Dipper", manufacturer: "Gretsch", year: 2018, description: "The Gretsch G9201 Honey Dipper Roundneck Metal Resonator is a stunning throwback to the earliest days of American music, with its all-brass body and old-timey tone and vintage looks. One strum of this Honey Dipper, and you are conjuring the past when traveling musicians roamed the country, playing for whoever would listen — hobo camps along the rails, or if they got a lucky break, live radio broadcasts from the earliest days of mega-watt stations. With a Gretsch Ampli-Sonic diaphragm biscuit resonator cone hand-spun in Eastern Europe, the Honey Dipper kicks out an impressive level of volume and mesmerizing midrange resonant tone. A gorgeous padauk fingerboard with abalone dot inlays responds beautifully whether you are playing chords or using a slide. The G9201 invites you to explore the styles of old country, blues, and early folk as well as whatever sonic innovations you can dream up. Resonator players at Sweetwater love the Honey Dipper Roundneck Metal Resonator for its playability and tone. Editors note: Ah, my first metal body resonator. Good Times.", category_id: 2},
  {name: "Swamp Dog Parlor", manufacturer: "Recording King", year: 2016, description: "The Swamp Dog Parlor has it all: classic resonator tone in a bell brass body, rusty vintage mojo, and one of the best-sounding resonator cones available.The Swamp Dog Parlor’s traditional resonator tone begins with a classic bell brass parlor-size body and RK’s own full-size hand-spun 9.5 inch cone.The Swamp Dog Parlor’s traditional resonator tone begins with a classic bell brass parlor-size body and RK’s own full-size hand-spun 9.5 inch cone", category_id: 2},
  {name: "Hound Dog", manufacturer: "Dobro", year: 2018, description: "With its classic Dobro lines, fully bound, highly figured maple wood body, and classic single cone resonator/spider bridge construction, the Gibson Original Dobro Hound Dog Deluxe Roundneck is stunning in both appearance and tone. In addition to the bridge's ebony saddle atop a maple base, the full, warm tone of the Hound Dog Deluxe Roundneck is enhanced and projected by a new proprietary Dobro cone and amplified via a Fishman resonator pickup. Combining classic construction with state-of-the-art electronics, the Hound Dog Deluxe Roundneck represents Gibson Original's deep respect for both the instrument's history and the needs of today's players. Case sold separately.", category_id: 3},
  {name: "RR-36 Maxwell Series", manufacturer: "Recording King", year: 2020, description: "The Recording King Maxwell Series RR-36 Resonator Acoustic is the perfect instrument for classic bluegrass and slide players looking to take the next step. The RR-36 Maxwell delivers true bluegrass tone thanks to the European hand-spun Recording King spider cone and a true sand cast spider bridge. The mahogany body and parallelogram soundwell help to produce crisp attack with minimal overtones, perfect for cutting through the band mix. Classic butterbean tuners conjure vintage mojo.", category_id: 3}
])
User.create!([
  {email: "test@test.com", username: "Test name", user_id: nil, password_digest: "$2a$12$6Huzbq0eSSbiOSp6sQH3m.PtbIaZOxC6DjJSEypLFq8ioee7zelZ2"},
  {email: "mrgame@gmail.com", username: "mrgame", user_id: nil, password_digest: "$2a$12$j5BCRr31dJsS7CJw52pD2eeoGiDVG7kSdvWRPrUffsErY6lF8mcke"},
  {email: "mrbrown@gmail.com", username: "mrbrown ", user_id: nil, password_digest: "$2a$12$2TVRVshq46Qwu7KwKaufNeQewrg5BneRzeqn.6KLLBlKEmDUU5BuW"},
  {email: "harrisonmarsh@gmail.com", username: "didi", user_id: nil, password_digest: "$2a$12$QFdrEhi.JDzd7N7Oxl0I4OEsSoiE/4lTVcE0W422n88HFzpGPCZDi"},
  {email: "maccoyle@gmail.com", username: "mcfc", user_id: nil, password_digest: "$2a$12$3.uc44DIVHv0lWzM6TP/pe60a.DM0vSFyGhxjtfYJTPUyp9OZkn6a"},
  {email: "test2@test.com", username: "Test 2 name", user_id: nil, password_digest: "$2a$12$T/.3oxfIPDgQ0zrSdX0JT.q/6w3TFA74waqLh0P8UleeDQXt6XBpe"}
])
